version: 2.1

workflows:
  build-and-test:
    jobs:
      - build:
          context: dockerauth

jobs:
  build:
    docker:
      - image: circleci/python:3.8
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    resource_class: small
    steps:
      - checkout
      - run: sudo pip install -r requirements.txt
      - run: pytest
